### ISSUE TITLE
opensearch SIGILL fatal error on `ddev start`

### ISSUE THREAD

**Issue by riconeitzel** [ddev/ddev-opensearch#10]
# Steps to Reproduce

* use macOS 15.2 (24C101)
* install limactl version 1.0.3
* install Docker version 27.5.0, build a187fa5d2d  
* install ddev version v1.24.2
* setup project `ddev config` … no further config required, simply confirm all steps
* install opensearch `ddev add-on get ddev/ddev-opensearch`
* run `ddev start`

# Expected Result

* systems fully starts, opensearch operational

# Actual Result

* `ddev start` breaks with fatal error in plugin installation

# Error Log

```
Building project images....failed to solve: process "/bin/sh -c if [ \"${INSTALL_PLUGIN_ANALYSIS_PHONETIC}\" = \"true\" ]; then bin/opensearch-plugin install analysis-phonetic; fi" did not complete successfully: exit code: 134

Failed to start os-test: docker-compose build failed: composeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-os-test docker-compose -f /Volumes/WebDev/temp/os-test/.ddev/.ddev-docker-compose-full.yaml --progress=plain build', action='[--progress=plain build]', err='exit status 17', stdout='#0 building with "default" instance using docker driver

#1 [db internal] load build definition from Dockerfile
#1 transferring dockerfile: 813B done
#1 DONE 0.0s

#2 [opensearch internal] load build definition from Dockerfile
#2 transferring dockerfile: 523B done
#2 DONE 0.0s

#3 [db internal] load metadata for docker.io/ddev/ddev-dbserver-mariadb-10.6:v1.24.2
#3 DONE 0.0s

#4 [db internal] load .dockerignore
#4 transferring context: 2B done
#4 DONE 0.0s

#5 [db 1/3] FROM docker.io/ddev/ddev-dbserver-mariadb-10.6:v1.24.2
#5 DONE 0.1s

#6 [db 2/3] RUN getent group tty || groupadd tty
#6 0.064 tty:x:5:
#6 DONE 0.2s

#7 [db 3/3] RUN (groupadd --gid 20 "rico" || groupadd "rico" || true) && (useradd -G tty -l -m -s "/bin/bash" --gid "rico" --comment '' --uid 501 "rico" || useradd -G tty -l -m -s "/bin/bash" --gid "rico" --comment '' "rico" || useradd  -G tty -l -m -s "/bin/bash" --gid "20" --comment '' "rico" || useradd -G tty -l -m -s "/bin/bash" --comment '' rico )
#7 0.073 groupadd: GID '20' already exists
#7 DONE 0.1s

#8 [db] resolving provenance for metadata file
#8 DONE 0.0s

#9 [db] exporting to image
#9 exporting layers done
#9 writing image sha256:6d55358524c7199d62f38975f5e332696929ee2a4c09876dada62fbb75af4c04 done
#9 naming to docker.io/ddev/ddev-dbserver-mariadb-10.6:v1.24.2-os-test-built done
#9 DONE 0.0s

#10 [opensearch internal] load metadata for docker.io/opensearchproject/opensearch:latest
#10 DONE 0.4s

#11 [opensearch internal] load .dockerignore
#11 transferring context: 2B done
#11 DONE 0.0s

#12 [opensearch 1/4] FROM docker.io/opensearchproject/opensearch:latest@sha256:7f6fa1efee8f39e94ca30a0a31f95d866c8a99f25a86e6cf6691142d1eab4f9e
#12 DONE 0.0s

#13 [opensearch 2/4] WORKDIR /usr/share/opensearch
#13 CACHED

#14 [opensearch 3/4] RUN if [ "true" = "true" ]; then bin/opensearch-plugin install analysis-phonetic; fi
#14 0.144 #
#14 0.144 # A fatal error has been detected by the Java Runtime Environment:
#14 0.144 #
#14 0.144 #  SIGILL (0x4) at pc=0x0000e774abd3fc5c, pid=26, tid=27
#14 0.144 #
#14 0.144 # JRE version:  (21.0.5+11) (build )
#14 0.144 # Java VM: OpenJDK 64-Bit Server VM (21.0.5+11-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-aarch64)
#14 0.144 # Problematic frame:
#14 0.144 # j  java.lang.System.registerNatives()V+0 java.base@21.0.5
#14 0.144 #
#14 0.144 # Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /usr/share/opensearch/core.26)
#14 0.144 #
#14 0.144 # An error report file with more information is saved as:
#14 0.144 # /usr/share/opensearch/hs_err_pid26.log
#14 0.146 [0.009s][warning][os] Loading hsdis library failed
#14 0.149 #
#14 0.149 # The crash happened outside the Java Virtual Machine in native code.
#14 0.149 # See problematic frame for where to report the bug.
#14 0.149 #
#14 0.197 bin/opensearch-env: line 99:    26 Aborted                 (core dumped) "$JAVA" "$XSHARE" -cp "$OPENSEARCH_CLASSPATH" org.opensearch.tools.java_version_checker.JavaVersionChecker
#14 ERROR: process "/bin/sh -c if [ \"${INSTALL_PLUGIN_ANALYSIS_PHONETIC}\" = \"true\" ]; then bin/opensearch-plugin install analysis-phonetic; fi" did not complete successfully: exit code: 134
------
 > [opensearch 3/4] RUN if [ "true" = "true" ]; then bin/opensearch-plugin install analysis-phonetic; fi:
0.144 # Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /usr/share/opensearch/core.26)
0.144 #
0.144 # An error report file with more information is saved as:
0.144 # /usr/share/opensearch/hs_err_pid26.log
0.146 [0.009s][warning][os] Loading hsdis library failed
0.149 #
0.149 # The crash happened outside the Java Virtual Machine in native code.
0.149 # See problematic frame for where to report the bug.
0.149 #
0.197 bin/opensearch-env: line 99:    26 Aborted                 (core dumped) "$JAVA" "$XSHARE" -cp "$OPENSEARCH_CLASSPATH" org.opensearch.tools.java_version_checker.JavaVersionChecker
------
', stderr='failed to solve: process "/bin/sh -c if [ \"${INSTALL_PLUGIN_ANALYSIS_PHONETIC}\" = \"true\" ]; then bin/opensearch-plugin install analysis-phonetic; fi" did not complete successfully: exit code: 134', output='#0 building with "default" instance using docker driver

#1 [db internal] load build definition from Dockerfile
#1 transferring dockerfile: 813B done
#1 DONE 0.0s

#2 [opensearch internal] load build definition from Dockerfile
#2 transferring dockerfile: 523B done
#2 DONE 0.0s

#3 [db internal] load metadata for docker.io/ddev/ddev-dbserver-mariadb-10.6:v1.24.2
#3 DONE 0.0s

#4 [db internal] load .dockerignore
#4 transferring context: 2B done
#4 DONE 0.0s

#5 [db 1/3] FROM docker.io/ddev/ddev-dbserver-mariadb-10.6:v1.24.2
#5 DONE 0.1s

#6 [db 2/3] RUN getent group tty || groupadd tty
#6 0.064 tty:x:5:
#6 DONE 0.2s

#7 [db 3/3] RUN (groupadd --gid 20 "rico" || groupadd "rico" || true) && (useradd -G tty -l -m -s "/bin/bash" --gid "rico" --comment '' --uid 501 "rico" || useradd -G tty -l -m -s "/bin/bash" --gid "rico" --comment '' "rico" || useradd  -G tty -l -m -s "/bin/bash" --gid "20" --comment '' "rico" || useradd -G tty -l -m -s "/bin/bash" --comment '' rico )
#7 0.073 groupadd: GID '20' already exists
#7 DONE 0.1s

#8 [db] resolving provenance for metadata file
#8 DONE 0.0s

#9 [db] exporting to image
#9 exporting layers done
#9 writing image sha256:6d55358524c7199d62f38975f5e332696929ee2a4c09876dada62fbb75af4c04 done
#9 naming to docker.io/ddev/ddev-dbserver-mariadb-10.6:v1.24.2-os-test-built done
#9 DONE 0.0s

#10 [opensearch internal] load metadata for docker.io/opensearchproject/opensearch:latest
#10 DONE 0.4s

#11 [opensearch internal] load .dockerignore
#11 transferring context: 2B done
#11 DONE 0.0s

#12 [opensearch 1/4] FROM docker.io/opensearchproject/opensearch:latest@sha256:7f6fa1efee8f39e94ca30a0a31f95d866c8a99f25a86e6cf6691142d1eab4f9e
#12 DONE 0.0s

#13 [opensearch 2/4] WORKDIR /usr/share/opensearch
#13 CACHED

#14 [opensearch 3/4] RUN if [ "true" = "true" ]; then bin/opensearch-plugin install analysis-phonetic; fi
#14 0.144 #
#14 0.144 # A fatal error has been detected by the Java Runtime Environment:
#14 0.144 #
#14 0.144 #  SIGILL (0x4) at pc=0x0000e774abd3fc5c, pid=26, tid=27
#14 0.144 #
#14 0.144 # JRE version:  (21.0.5+11) (build )
#14 0.144 # Java VM: OpenJDK 64-Bit Server VM (21.0.5+11-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-aarch64)
#14 0.144 # Problematic frame:
#14 0.144 # j  java.lang.System.registerNatives()V+0 java.base@21.0.5
#14 0.144 #
#14 0.144 # Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /usr/share/opensearch/core.26)
#14 0.144 #
#14 0.144 # An error report file with more information is saved as:
#14 0.144 # /usr/share/opensearch/hs_err_pid26.log
#14 0.146 [0.009s][warning][os] Loading hsdis library failed
#14 0.149 #
#14 0.149 # The crash happened outside the Java Virtual Machine in native code.
#14 0.149 # See problematic frame for where to report the bug.
#14 0.149 #
#14 0.197 bin/opensearch-env: line 99:    26 Aborted                 (core dumped) "$JAVA" "$XSHARE" -cp "$OPENSEARCH_CLASSPATH" org.opensearch.tools.java_version_checker.JavaVersionChecker
#14 ERROR: process "/bin/sh -c if [ \"${INSTALL_PLUGIN_ANALYSIS_PHONETIC}\" = \"true\" ]; then bin/opensearch-plugin install analysis-phonetic; fi" did not complete successfully: exit code: 134
------
 > [opensearch 3/4] RUN if [ "true" = "true" ]; then bin/opensearch-plugin install analysis-phonetic; fi:
0.144 # Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /usr/share/opensearch/core.26)
0.144 #
0.144 # An error report file with more information is saved as:
0.144 # /usr/share/opensearch/hs_err_pid26.log
0.146 [0.009s][warning][os] Loading hsdis library failed
0.149 #
0.149 # The crash happened outside the Java Virtual Machine in native code.
0.149 # See problematic frame for where to report the bug.
0.149 #
0.197 bin/opensearch-env: line 99:    26 Aborted                 (core dumped) "$JAVA" "$XSHARE" -cp "$OPENSEARCH_CLASSPATH" org.opensearch.tools.java_version_checker.JavaVersionChecker
------
', stderr='failed to solve: process "/bin/sh -c if [ \"${INSTALL_PLUGIN_ANALYSIS_PHONETIC}\" = \"true\" ]; then bin/opensearch-plugin install analysis-phonetic; fi" did not complete successfully: exit code: 134'
```

**Comment by riconeitzel** [comment]
ℹ  even if the plugin installation from `DOCKERFILE` is removed, the SIGILL still occurs, just at another point:

```
Disabling OpenSearch Security Plugin
Enabling execution of OPENSEARCH_HOME/bin/opensearch-performance-analyzer/performance-analyzer-agent-cli for OpenSearch Performance Analyzer Plugin
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x0000efaf17d3fc5c, pid=35, tid=37
#
# JRE version:  (21.0.5+11) (build )
# Java VM: OpenJDK 64-Bit Server VM (21.0.5+11-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-aarch64)
# Problematic frame:
# j  java.lang.System.registerNatives()V+0 java.base@21.0.5
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /usr/share/opensearch/core.35)
#
# An error report file with more information is saved as:
# /usr/share/opensearch/hs_err_pid35.log
[0.011s][warning][os] Loading hsdis library failed
#
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
/usr/share/opensearch/bin/opensearch-env: line 99:    35 Aborted                 (core dumped) "$JAVA" "$XSHARE" -cp "$OPENSEARCH_CLASSPATH" org.opensearch.tools.java_version_checker.JavaVersionChecker
```

**Comment by cmuench** [comment]
Seems related to this upstream issue: https://github.com/opensearch-project/OpenSearch/issues/16761
The described workaround is to set the env variable `OPENSEARCH_JAVA_OPTS=-XX:UseSVE=0`.
The issue is only on Mac with ARM.

**Comment by cmuench** [comment]
@riconeitzel Can you try to set `OPENSEARCH_JAVA_OPTS=-XX:UseSVE=0` in the `docker-compose.opensearch.yaml` and re-start the project?

**Comment by riconeitzel** [comment]
Hi @cmuench thanks for your help. Tried it but it didn't work. But it corresponds: I'm using an apple silicon mac.

**Comment by rfay** [comment]
SIGKILL is most often a result of an out-of-memory condition. You're using Lima, but you don't say how much memory you allocated to it. Please check and see if allocating more solves the problem.

**Comment by riconeitzel** [comment]
Hi @rfay, thanks for your hint. I believe it's enough: 

```
cpus: 4
memory: 16GiB
mountType: virtiofs
disk: 250GiB
vmType: vz
```

I noticed that the issue is not present in Version 2.10.0 of the opensearch image. I assume there are some things updated in the image between 2.10.0 and 2.16.0 (didn't try other versions yet, but I'm happy to do so if it helps.)

I assume @cmuench is on the right track, but I was not be successful with the fixes they mentioned in the upstream issue.

**Comment by stasadev** [comment]
People in the [relevant issue](https://github.com/opensearch-project/OpenSearch/issues/16761#issuecomment-2565680315) have succeeded with:

```yaml
services:
  opensearch:
    environment:
      - _JAVA_OPTIONS=-XX:UseSVE=0
```

**Comment by riconeitzel** [comment]
Hi @stasadev - thanks for your message as well!

that's my yaml file at the moment:

```
services:
  opensearch:
    container_name: ddev-${DDEV_SITENAME}-opensearch
    build: 
      context: ./opensearch
      dockerfile: Dockerfile
      args:
        OPENSEARCH_TAG: ${OPENSEARCH_TAG:-latest}
        INSTALL_PLUGIN_ANALYSIS_PHONETIC: ${INSTALL_PLUGIN_ANALYSIS_PHONETIC:-true}
        INSTALL_PLUGIN_ANALYSIS_ICU: ${INSTALL_PLUGIN_ANALYSIS_ICU:-true}
    expose:
      - 9200
    environment:
      # disables installation of demo data
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      # disables security plugin
      - "DISABLE_SECURITY_PLUGIN=true"
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=9200:9200
      - HTTPS_EXPOSE=9201:9200
      - _JAVA_OPTIONS=-XX:UseSVE=0
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - opensearch:/usr/share/opensearch/data
      - ".:/mnt/ddev_config"
      - "ddev-global-cache:/mnt/ddev-global-cache"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -s localhost:9200"]

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:${OPENSEARCH_DASHBOARDS_TAG:-latest}
    container_name: 'ddev-${DDEV_SITENAME}-opensearch-dashboards'
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - OPENSEARCH_HOSTS=http://ddev-${DDEV_PROJECT}-opensearch:9200
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true" # disables security plugin
      - HTTP_EXPOSE=5601:5601
      - HTTPS_EXPOSE=5602:5601
    expose:
      - 5601
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    depends_on:
      - opensearch

  web:
    depends_on:
      - opensearch

volumes:
  opensearch:
```

but still it causes the same issue with the latest opensearch images.
